name: Issue Report
description: File a bug report or ask a question
title: "[Bug/Question] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        The issue tracker is not for feature requests, please add your idea to MarkBench [forum thread](https://linustechtips.com/topic/1460878-markbench-development-and-feature-requests/)
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **MarkBench Test Version**: 1.0.0
          - **OS**: Windows 11 22H2
          - **GPU**: GTX 1070 Ti
          - **CPU**: Intel i7 8700K
      value: |
          - MarkBench Test Version:
          - OS:
          - GPU:
          - CPU:
      render: markdown
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
